# Generated by Django 5.2.7 on 2025-10-28 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='group',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='members',
        ),
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal Split'), ('exact', 'Exact Amount'), ('percentage', 'Percentage Split')], default='equal', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(related_name='expenses_participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
