# Generated by Django 5.2.7 on 2025-11-12 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0008_expensecategory_alter_expense_options_and_more'),
        ('groups', '0002_group_created_by_group_end_date_group_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_added', models.BooleanField(default=True)),
                ('expense_edited', models.BooleanField(default=True)),
                ('expense_deleted', models.BooleanField(default=True)),
                ('payment_received', models.BooleanField(default=True)),
                ('payment_reminder', models.BooleanField(default=True)),
                ('group_invite', models.BooleanField(default=True)),
                ('member_changes', models.BooleanField(default=True)),
                ('email_expense_added', models.BooleanField(default=True)),
                ('email_payment_received', models.BooleanField(default=True)),
                ('email_payment_reminder', models.BooleanField(default=True)),
                ('email_group_invite', models.BooleanField(default=True)),
                ('email_digest', models.BooleanField(default=False)),
                ('email_digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('expense_added', 'Expense Added'), ('expense_edited', 'Expense Edited'), ('expense_deleted', 'Expense Deleted'), ('payment_received', 'Payment Received'), ('payment_reminder', 'Payment Reminder'), ('group_invite', 'Group Invite'), ('member_added', 'Member Added to Group'), ('member_removed', 'Member Removed from Group'), ('comment_added', 'Comment Added')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='expenses.expense')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='groups.group')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
